### ISSUE TITLE
Feature #1: User can search up their Long & Lat 

### ISSUE THREAD

**Issue by Gallegos22** [Gallegos22/Sunsets-FAR-and-NEAR#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click on a link that will navigate them to a different website that will convert their zipcode to lat & long. After that they will copy and paste it back in the search bar of the website I created.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a header and make a `<div> `
- [x] within the `<div>` add a list icon the user can eventually click on to view their sunsets viewed
- [x] after the header create some text using a `<p>` tag and then use an anchor tag to create the link to the other website that converts zip code's to lat & long
- [x] create a label followed by an input to have my lat and long
- [x] create a button called 'search' that will eventually get data from my API but for now just create it 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
